area/adapter:
  - adapters/**/*

area/architecture:
  - architectures/**/*

area/task:
  - tasks/**/*
  - subtasks/**/*

area/core:
  - /*
  - scripts/**/*
  - adapter_types/**/*

"**invalid**":
  - dist/**/*
  - adapters/*
