id: pfeiffer
displayname: Pfeiffer Architecture
description: |
  Original Pfeiffer adapter architecture for task and language adapters with reduction factor 16.

citation: |
  @misc{pfeiffer2020adapterfusion,
    title={AdapterFusion: Non-Destructive Task Composition for Transfer Learning},
    author={Jonas Pfeiffer and Aishwarya Kamath and Andreas Rücklé and Kyunghyun Cho and Iryna Gurevych},
    year={2020},
    eprint={2005.00247},
    archivePrefix={arXiv},
    primaryClass={cs.CL}
  }

config:
  {
    "LN_after": false,
    "LN_before": false,
    "MH_Adapter": false,
    "Output_Adapter": true,
    "adapter_residual_before_ln": false,
    "attention_type": "sent-lvl-dynamic",
    "new_attention_norm": false,
    "non_linearity": "relu",
    "original_ln_after": true,
    "original_ln_before": true,
    "reduction_factor": 16,
    "residual_before_ln": true,
    "invertible_adapter":
      { "block_type": "nice", "non_linearity": "relu", "reduction_factor": 2 },
  }
