name: Adapter Checks

on:
  pull_request:
    branches: [ master ]
    paths: [ 'repo/**' ]

jobs:
  # Check if the file format seems valid
  check_format:
    name: Config file format
    runs-on: ubuntu-latest
    # output changed files for the next step
    outputs:
      added_modified: ${{ steps.files.outputs.added_modified }}
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install
        run: |
          pip install jsonschema
      - name: Run format checking
        run: |
          python scripts/check_format.py ${{ steps.files.outputs.added_modified }}
  # Check if the provided download links refer to valid weights
  check_download_files:
    name: Download files
    runs-on: ubuntu-latest
    needs: check_format
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Framework
        run: |
          pip install torch
          pip install git+https://github.com/calpt/adapter-transformers.git
      - name: Check download files
        run: |
          python scripts/check_download_files.py ${{ needs.check_format.outputs.added_modified }}
