name: Trigger website build

on:
  push:
    branches: [ master ]
    paths: [ 'adapter_types/**', 'tasks/**', 'subtasks/**' ]

jobs:
  repository_dispatch:
    # TODO change when moving
    if: github.repository_owner == 'calpt'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: Adapter-Hub/website
          event-type: build
